development:
  adapter: postgresql
  encoding: unicode
  database: playtime
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: playtime
  pool: 5
  username: postgres
  password: postgres
  host: localhost